### PR TITLE
Change alligator to lizard.

### PR DESCRIPTION
**Pull request by ocinyb**

### CODE REVIEW

**Comment by mikeckennedy** [comment]
Why are we changing to lizard? :)

**Comment by ocinyb** [comment]
> Why are we changing to lizard? :)

Cuteness? :D

(Sorry just a test)

**Comment by mikeckennedy** [comment]
Ha, no problem. However, I do want to keep it the same as what was presented in the videos.

**Comment by ocinyb** [comment]
Sure. Thanks for the course! Amazing job!

**Pull request closed without merging**
